### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by OrionRandD** [Gavinok/emacs.d#1]
Not an issue, but a suggestion:
Just a commentary on your video: "You should learn orgmode. It is easy"
Yes, orgmode is wonderful. But, in some aspects "eev" is much better and efficient.
Although it is not so popular...
I suggest you to study it and start using it; talk to his author, perhaps through telegram. He is available to teach it...
http://angg.twu.net/#eev
And, who knows? 
Make a video series about it...
If you understand the inwardness of it.  ;)

**Comment by Gavinok** [comment]
Thank you for the suggestion
