### ISSUE TITLE
Cape-yasnippet issue

### ISSUE THREAD

**Issue by fleurc** [Gavinok/emacs.d#2]
Today after coming across your video about completion, i decided to take a look at your config and copy paste the Completion section.

Tho it initially worked (after i fixed the Quelpa dependency) the auto complete of Corfu failed after Quelpa was installed. I tested everything and it seems the line breaks the config:

```emacs-lisp
:config
  (defun yas-setup-capf ()
    (setq-local completion-at-point-functions
                (cons 'cape-yasnippet
                      completion-at-point-functions)))
``` 
Could you at some point explain why use cape-yasnippet? I have gone to its page and it seems to have nothing aside from a single file, not even an explanation on its utility.

**Comment by Gavinok** [comment]
I ended up dropping this. I was using it to allow corfu to display yasnippets. I no longer use this though and have switched to https://github.com/minad/tempel
